//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Domain.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado. Você não tem permissão para visualizar este recurso..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ao persistir dados no banco de dados..
        /// </summary>
        public static string inventoryCreationError {
            get {
                return ResourceManager.GetString("inventoryCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao recuperar os itens de inventário do banco de dados..
        /// </summary>
        public static string inventoryRetrievalError {
            get {
                return ResourceManager.GetString("inventoryRetrievalError", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Ocorreu um erro ao deletar o item de inventário do banco de dados..
        ///     
        public static string inventoryDeletionError
        {
            get
            {
                return ResourceManager.GetString("inventoryDeletionError", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Ocorreu um erro ao atualizar o item de inventário no banco de dados..
        /// 
        public static string inventoryUpdateError
        {
            get
            {
                return ResourceManager.GetString("inventoryUpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audiência inválida na configuração do Keycloak. Verifique os parâmetros do token..
        /// </summary>
        public static string KEYCLOACK_INVALID_AUDIENCE {
            get {
                return ResourceManager.GetString("KEYCLOACK_INVALID_AUDIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração inválida do Keycloak. Verifique as credenciais e os parâmetros de autenticação..
        /// </summary>
        public static string KEYCLOACK_INVALID_CONFIG {
            get {
                return ResourceManager.GetString("KEYCLOACK_INVALID_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asd.
        /// </summary>
        public static string POLICY_PREFIX {
            get {
                return ResourceManager.GetString("POLICY_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao acessar o  banco de dados PostgreSQL..
        /// </summary>
        public static string postgresInventoryError {
            get {
                return ResourceManager.GetString("postgresInventoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão para realizar esta ação..
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
